ifdef CONFIG_DIFFTEST
DIFFTEST_REF_PATH = $(METEOR_ENV_HOME)/core/$(CFG_DIFFTEST_REF_PATH)
DIFFTEST_REF_SO   = $(DIFFTEST_REF_PATH)/build/$(CFG_GUEST_ISA)-$(CFG_DIFFTEST_REF_NAME)-so
MKFLAGS = GUEST_ISA=$(CFG_GUEST_ISA) SHARE=1 ENGINE=interpreter
ARGS_DIFF = -d $(DIFFTEST_REF_SO)

ifndef CONFIG_DIFFTEST_REF_MEMU
$(DIFFTEST_REF_SO):
	$(MAKE) -s -C $(DIFFTEST_REF_PATH) $(MKFLAGS)
endif

.PHONY: $(DIFFTEST_REF_SO)
endif
